apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: say-hello
      image: registry.redhat.io/ubi8
      command:
        - /bin/bash
      args: ['-c', 'echo Hello World']
