apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: say-hello
      image: registry.access.redhat.com/ubi8:8.8-1067
      command:
        - /bin/bash
      args: ['-c', 'echo Hello World']
